export const MPS = [
  {
    firstName: 'Deepak',
    lastName: 'Anand',

    email: 'deepak.anand@pc.ola.org',

    ridingName: 'Mississauga—Malton',
  },
  {
    firstName: 'Jill',
    lastName: 'Andrew',

    email: 'JAndrew-QP@ndp.on.ca',

    ridingName: "Toronto—St. Paul's",
  },
  {
    firstName: 'Teresa',
    lastName: 'Armstrong',

    email: 'tarmstrong-qp@ndp.on.ca',
    ridingName: 'London—Fanshawe',
  },

  {
    firstName: 'Ted',
    lastName: 'Arnott',
    email: 'ted.arnott@pc.ola.org',

    ridingName: 'Wellington—Halton Hills',
  },
  {
    firstName: 'Ian',
    lastName: 'Arthur',

    email: 'IArthur-QP@ndp.on.ca',

    ridingName: 'Kingston and the Islands',
  },
  {
    firstName: 'Roman',
    lastName: 'Baber',

    email: 'rbaber@ola.org',

    ridingName: 'York Centre',
  },
  {
    firstName: 'Aris',
    lastName: 'Babikian',

    email: 'aris.babikian@pc.ola.org',

    ridingName: 'Scarborough—Agincourt',
  },
  {
    firstName: 'Toby',
    lastName: 'Barrett',
    email: 'toby.barrett@pc.ola.org',
    ridingName: 'Haldimand—Norfolk',
  },
  {
    firstName: 'Doly',
    lastName: 'Begum',
    email: 'DBegum-QP@ndp.on.ca',
    ridingName: 'Scarborough Southwest',
  },
  {
    firstName: 'Jessica',
    lastName: 'Bell',
    email: 'JBell-QP@ndp.on.ca',
    ridingName: 'University—Rosedale',
  },
  {
    firstName: 'Rima',
    lastName: 'Berns-McGown',
    email: 'RBerns-McGown-QP@ndp.on.ca',
    ridingName: 'Beaches—East York',
  },
  {
    firstName: 'Peter',
    lastName: 'Bethlenfalvy',
    email: 'peter.bethlenfalvy@pc.ola.org',
    ridingName: 'Pickering—Uxbridge',
  },
  {
    firstName: 'Gilles',
    lastName: 'Bisson',
    email: 'gbisson@ndp.on.ca',
    ridingName: 'Timmins',
  },
  {
    firstName: 'Stephen',
    lastName: 'Blais',
    email: 'sblais.mpp.co@liberal.ola.org',
    ridingName: 'Orléans',
  },
  {
    firstName: 'Will',
    lastName: 'Bouma',
    email: 'will.bouma@pc.ola.org',
    ridingName: 'Brantford—Brant',
  },
  {
    firstName: 'Guy',
    lastName: 'Bourgouin',
    email: 'GBourgouin-QP@ndp.on.ca',
    ridingName: 'Mushkegowuk—James Bay',
  },
  {
    firstName: 'Jeff',
    lastName: 'Burch',
    email: 'JBurch-QP@ndp.on.ca',
    ridingName: 'Niagara Centre',
  },
  {
    firstName: 'Paul',
    lastName: 'Calandra',
    email: 'paul.calandra@pc.ola.org',
    ridingName: 'Markham—Stouffville',
  },
  {
    firstName: 'Raymond Sung Joon',
    lastName: 'Cho',
    email: 'raymond.cho@pc.ola.org',
    ridingName: 'Scarborough North',
  },
  {
    firstName: 'Stan',
    lastName: 'Cho',
    email: 'stan.cho@pc.ola.org',
    ridingName: 'Willowdale',
  },
  {
    firstName: 'Steve',
    lastName: 'Clark',
    email: 'steve.clark@pc.ola.org',
    ridingName: 'Leeds—Grenville—Thousand Islands and Rideau Lakes',
  },
  {
    firstName: 'Lorne',
    lastName: 'Coe',
    email: 'lorne.coe@pc.ola.org',
    ridingName: 'Whitby',
  },
  {
    firstName: 'Lucille',
    lastName: 'Collard',
    email: 'LCollard.mpp.co@liberal.ola.org',
    ridingName: 'Ottawa—Vanier',
  },
  {
    firstName: 'Michael',
    lastName: 'Coteau',
    email: 'mcoteau.mpp.co@liberal.ola.org',
    ridingName: 'Don Valley East',
  },
  {
    firstName: 'Stephen',
    lastName: 'Crawford',
    email: 'stephen.crawford@pc.ola.org',
    ridingName: 'Oakville',
  },
  {
    firstName: 'Rudy',
    lastName: 'Cuzzetto',
    email: 'rudy.cuzzetto@pc.ola.org',
    ridingName: 'Mississauga—Lakeshore',
  },
  {
    firstName: 'Doug',
    lastName: 'Downey',
    email: 'doug.downey@pc.ola.org',
    ridingName: 'Barrie—Springwater—Oro-Medonte',
  },
  {
    firstName: 'Jill',
    lastName: 'Dunlop',
    email: 'jill.dunlop@pc.ola.org',
    ridingName: 'Simcoe North',
  },

  {
    firstName: 'Christine',
    lastName: 'Elliott',
    email: 'christine.elliott@pc.ola.org',
    ridingName: 'Newmarket—Aurora',
  },
  {
    firstName: 'Victor',
    lastName: 'Fedeli',
    email: 'vic.fedeli@pc.ola.org',
    ridingName: 'Nipissing',
  },
  {
    firstName: 'Amy',
    lastName: 'Fee',
    email: 'amy.fee@pc.ola.org',
    ridingName: 'Kitchener South—Hespeler',
  },
  {
    firstName: 'Catherine',
    lastName: 'Fife',
    email: 'cfife-qp@ndp.on.ca',
    ridingName: 'Waterloo',
  },
  {
    firstName: 'Doug',
    lastName: 'Ford',
    email: 'doug.fordco@pc.ola.org',
    ridingName: 'Etobicoke North',
  },
  {
    firstName: 'John',
    lastName: 'Fraser',
    email: 'Jfraser.mpp.co@liberal.ola.org',
    ridingName: 'Ottawa South',
  },
  {
    firstName: 'Jennifer',
    lastName: 'French',
    email: 'JFrench-QP@ndp.on.ca',
    ridingName: 'Oshawa',
  },
  {
    firstName: 'Merrilee',
    lastName: 'Fullerton',
    email: 'merrilee.fullerton@pc.ola.org',
    ridingName: 'Kanata—Carleton',
  },
  {
    firstName: 'Wayne',
    lastName: 'Gates',
    email: 'wgates-qp@ndp.on.ca',
    ridingName: 'Niagara Falls',
  },
  {
    firstName: 'Goldie',
    lastName: 'Ghamari',
    email: 'goldie.ghamari@pc.ola.org',
    ridingName: 'Carleton',
  },
  {
    firstName: 'Parm',
    lastName: 'Gill',
    email: 'parm.gill@pc.ola.org',
    ridingName: 'Milton',
  },
  {
    firstName: 'Chris',
    lastName: 'Glover',
    email: 'CGlover-CO@ndp.on.ca',
    ridingName: 'Spadina—Fort York',
  },
  {
    firstName: 'Michael',
    lastName: 'Gravelle',
    email: 'mgravelle.mpp.co@liberal.ola.org',
    ridingName: 'Thunder Bay—Superior North',
  },
  {
    firstName: 'Lisa',
    lastName: 'Gretzky',
    email: 'LGretzky-QP@ndp.on.ca',
    ridingName: 'Windsor West',
  },
  {
    firstName: 'France',
    lastName: 'Gélinas',
    email: 'fgelinas-qp@ndp.on.ca',
    ridingName: 'Nickel Belt',
  },
  {
    firstName: 'Ernie',
    lastName: 'Hardeman',
    email: 'ernie.hardeman@pc.ola.org',
    ridingName: 'Oxford',
  },
  {
    firstName: 'Joel',
    lastName: 'Harden',
    email: 'JHarden-QP@ndp.on.ca',
    ridingName: 'Ottawa Centre',
  },
  {
    firstName: 'Mike',
    lastName: 'Harris',
    email: 'mike.harris@pc.ola.org',
    ridingName: 'Kitchener—Conestoga',
  },
  {
    firstName: 'Faisal',
    lastName: 'Hassan',
    email: 'FHassan-QP@ndp.on.ca',
    ridingName: 'York South—Weston',
  },
  {
    firstName: 'Percy',
    lastName: 'Hatfield',
    email: 'PHatfield-QP@ndp.on.ca',
    ridingName: 'Windsor—Tecumseh',
  },
  {
    firstName: 'Randy',
    lastName: 'Hillier',
    email: 'RHillier-CO@ola.org',
    ridingName: 'Lanark—Frontenac—Kingston',
  },
  {
    firstName: 'Christine',
    lastName: 'Hogarth',
    email: 'christine.hogarth@pc.ola.org',
    ridingName: 'Etobicoke—Lakeshore',
  },
  {
    firstName: 'Andrea',
    lastName: 'Horwath',
    email: 'horwatha-qp@ndp.on.ca',
    ridingName: 'Hamilton Centre',
  },
  {
    firstName: 'Mitzie',
    lastName: 'Hunter',
    email: 'mhunter.mpp.co@liberal.ola.org',
    ridingName: 'Scarborough—Guildwood',
  },
  {
    firstName: 'Sylvia',
    lastName: 'Jones',
    email: 'sylvia.jones@pc.ola.org',
    ridingName: 'Dufferin—Caledon',
  },
  {
    firstName: 'Logan',
    lastName: 'Kanapathi',
    email: 'logan.kanapathi@pc.ola.org',
    ridingName: 'Markham—Thornhill',
  },
  {
    firstName: 'Belinda',
    lastName: 'Karahalios',
    email: 'bkarahalios@ola.org',
    ridingName: 'Cambridge',
  },
  {
    firstName: 'Bhutila',
    lastName: 'Karpoche',
    email: 'BKarpoche-QP@ndp.on.ca',
    ridingName: 'Parkdale—High Park',
  },
  {
    firstName: 'Vincent',
    lastName: 'Ke',
    email: 'vincent.ke@pc.ola.org',
    ridingName: 'Don Valley North',
  },
  {
    firstName: 'Terence',
    lastName: 'Kernaghan',
    email: 'TKernaghan-QP@ndp.on.ca',
    ridingName: 'London North Centre',
  },
  {
    firstName: 'Andrea',
    lastName: 'Khanjin',
    email: 'andrea.khanjin@pc.ola.org',
    ridingName: 'Barrie—Innisfil',
  },
  {
    firstName: 'Daryl',
    lastName: 'Kramp',
    email: 'daryl.kramp@pc.ola.org',
    ridingName: 'Hastings—Lennox and Addington',
  },
  {
    firstName: 'Natalia',
    lastName: 'Kusendova',
    email: 'natalia.kusendova@pc.ola.org',
    ridingName: 'Mississauga Centre',
  },
  {
    firstName: 'Stephen',
    lastName: 'Lecce',
    email: 'stephen.lecce@pc.ola.org',
    ridingName: 'King—Vaughan',
  },

  {
    firstName: 'Laura Mae',
    lastName: 'Lindo',
    email: 'LLindo-QP@ndp.on.ca',
    ridingName: 'Kitchener Centre',
  },
  {
    firstName: 'Lisa',
    lastName: 'MacLeod',
    email: 'Lisa.macleodco@pc.ola.org',
    ridingName: 'Nepean',
  },
  {
    firstName: 'Sol',
    lastName: 'Mamakwa',
    email: 'SMamakwa-QP@ndp.on.ca',
    ridingName: 'Kiiwetinoong',
  },
  {
    firstName: 'Michael',
    lastName: 'Mantha',
    email: 'mmantha-qp@ndp.on.ca',
    ridingName: 'Algoma—Manitoulin',
  },
  {
    firstName: 'Robin',
    lastName: 'Martin',
    email: 'robin.martin@pc.ola.org',
    ridingName: 'Eglinton—Lawrence',
  },
  {
    firstName: 'Gila',
    lastName: 'Martow',
    email: 'gila.martow@pc.ola.org',
    ridingName: 'Thornhill',
  },
  {
    firstName: 'Jim',
    lastName: 'McDonell',
    email: 'jim.mcdonell@pc.ola.org',
    ridingName: 'Stormont—Dundas—South Glengarry',
  },
  {
    firstName: 'Jane',
    lastName: 'McKenna',
    email: 'jane.mckenna@pc.ola.org',
    ridingName: 'Burlington',
  },
  {
    firstName: 'Monte',
    lastName: 'McNaughton',
    email: 'monte.mcnaughtonco@pc.ola.org',
    ridingName: 'Lambton—Kent—Middlesex',
  },
  {
    firstName: 'Norman',
    lastName: 'Miller',
    email: 'norm.miller@pc.ola.org',
    ridingName: 'Parry Sound—Muskoka',
  },
  {
    firstName: 'Paul',
    lastName: 'Miller',
    email: 'pmiller-qp@ndp.on.ca',
    ridingName: 'Hamilton East—Stoney Creek',
  },
  {
    firstName: 'Christina',
    lastName: 'Mitas',
    email: 'christina.mitas@pc.ola.org',
    ridingName: 'Scarborough Centre',
  },
  {
    firstName: 'Judith',
    lastName: 'Monteith-Farrell',
    email: 'JMonteith-Farrell-QP@ndp.on.ca',
    ridingName: 'Thunder Bay—Atikokan',
  },
  {
    firstName: 'Suze',
    lastName: 'Morrison',
    email: 'SMorrison-QP@ndp.on.ca',
    ridingName: 'Toronto Centre',
  },

  {
    firstName: 'Caroline',
    lastName: 'Mulroney',
    email: 'caroline.mulroney@pc.ola.org',
    ridingName: 'York—Simcoe',
  },

  {
    firstName: 'Taras',
    lastName: 'Natyshak',
    email: 'tnatyshak-qp@ndp.on.ca',
    ridingName: 'Essex',
  },
  {
    firstName: 'Rick',
    lastName: 'Nicholls',
    email: 'rick.nicholls@pc.ola.org',
    ridingName: 'Chatham-Kent—Leamington',
  },
  {
    firstName: 'Sam',
    lastName: 'Oosterhoff',
    email: 'sam.oosterhoff@pc.ola.org',
    ridingName: 'Niagara West',
  },
  {
    firstName: 'Billy',
    lastName: 'Pang',
    email: 'billy.pang@pc.ola.org',
    ridingName: 'Markham—Unionville',
  },
  {
    firstName: 'Lindsey',
    lastName: 'Park',
    email: 'lindsey.park@pc.ola.org',
    ridingName: 'Durham',
  },
  {
    firstName: 'Michael',
    lastName: 'Parsa',
    email: 'michael.parsaco@pc.ola.org',
    ridingName: 'Aurora—Oak Ridges—Richmond Hill',
  },
  {
    firstName: 'Randy',
    lastName: 'Pettapiece',
    email: 'randy.pettapiece@pc.ola.org',
    ridingName: 'Perth—Wellington',
  },
  {
    firstName: 'Rod',
    lastName: 'Phillips',
    email: 'rod.phillips@pc.ola.org',
    ridingName: 'Ajax',
  },
  {
    firstName: 'David',
    lastName: 'Piccini',
    email: 'david.piccini@pc.ola.org',
    ridingName: 'Northumberland—Peterborough South',
  },

  {
    firstName: 'Tom',
    lastName: 'Rakocevic',
    email: 'TRakocevic-QP@ndp.on.ca',
    ridingName: 'Humber River—Black Creek',
  },
  {
    firstName: 'Kaleed',
    lastName: 'Rasheed',
    email: 'kaleed.rasheed@pc.ola.org',
    ridingName: 'Mississauga East—Cooksville',
  },
  {
    firstName: 'Greg',
    lastName: 'Rickford',
    email: 'greg.rickford@pc.ola.org',
    ridingName: 'Kenora—Rainy River',
  },
  {
    firstName: 'Jeremy',
    lastName: 'Roberts',
    email: 'jeremy.roberts@pc.ola.org',
    ridingName: 'Ottawa West—Nepean',
  },

  {
    firstName: 'Ross',
    lastName: 'Romano',
    email: 'ross.romano@pc.ola.org',
    ridingName: 'Sault Ste. Marie',
  },
  {
    firstName: 'Sheref',
    lastName: 'Sabawy',
    email: 'sheref.sabawy@pc.ola.org',
    ridingName: 'Mississauga—Erin Mills',
  },

  {
    firstName: 'Amarjot',
    lastName: 'Sandhu',
    email: 'amarjot.sandhu@pc.ola.org',
    ridingName: 'Brampton West',
  },
  {
    firstName: 'Prabmeet Singh',
    lastName: 'Sarkaria',
    email: 'prabmeet.sarkaria@pc.ola.org',
    ridingName: 'Brampton South',
  },

  {
    firstName: 'Peggy',
    lastName: 'Sattler',
    email: 'Psattler-qp@ndp.on.ca',
    ridingName: 'London West',
  },
  {
    firstName: 'Mike',
    lastName: 'Schreiner',
    email: 'Mschreiner@ola.org',
    ridingName: 'Guelph',
  },
  {
    firstName: 'Laurie',
    lastName: 'Scott',
    email: 'laurie.scott@pc.ola.org',
    ridingName: 'Haliburton—Kawartha Lakes—Brock',
  },
  {
    firstName: 'Sandy',
    lastName: 'Shaw',
    email: 'SShaw-CO@ndp.on.ca',
    ridingName: 'Hamilton West—Ancaster—Dundas',
  },
  {
    firstName: 'Amanda',
    lastName: 'Simard',
    email: 'asimard.mpp@liberal.ola.org',
    ridingName: 'Glengarry—Prescott—Russell',
  },
  {
    firstName: 'Gurratan',
    lastName: 'Singh',
    email: 'GSingh-QP@ndp.on.ca',
    ridingName: 'Brampton East',
  },
  {
    firstName: 'Sara',
    lastName: 'Singh',
    email: 'SSingh-QP@ndp.on.ca',
    ridingName: 'Brampton Centre',
  },
  {
    firstName: 'Donna',
    lastName: 'Skelly',
    email: 'donna.skelly@pc.ola.org',
    ridingName: 'Flamborough—Glanbrook',
  },
  {
    firstName: 'Dave',
    lastName: 'Smith',
    email: 'dave.smith@pc.ola.org',
    ridingName: 'Peterborough—Kawartha',
  },
  {
    firstName: 'Todd',
    lastName: 'Smith',
    email: 'todd.smithco@pc.ola.org',
    ridingName: 'Bay of Quinte',
  },
  {
    firstName: 'Jennifer (Jennie)',
    lastName: 'Stevens',
    email: 'JStevens-QP@ndp.on.ca',
    ridingName: 'St. Catharines',
  },
  {
    firstName: 'Marit',
    lastName: 'Stiles',
    email: 'MStiles-QP@ndp.on.ca',
    ridingName: 'Davenport',
  },
  {
    firstName: 'Kinga',
    lastName: 'Surma',
    email: 'kinga.surma@pc.ola.org',
    ridingName: 'Etobicoke Centre',
  },
  {
    firstName: 'Peter',
    lastName: 'Tabuns',
    email: 'tabunsp-qp@ndp.on.ca',
    ridingName: 'Toronto—Danforth',
  },
  {
    firstName: 'Nina',
    lastName: 'Tangri',
    email: 'nina.tangri@pc.ola.org',
    ridingName: 'Mississauga—Streetsville',
  },
  {
    firstName: 'Monique',
    lastName: 'Taylor',
    email: 'mtaylor-qp@ndp.on.ca',
    ridingName: 'Hamilton Mountain',
  },
  {
    firstName: 'Vijay',
    lastName: 'Thanigasalam',
    email: 'vijay.thanigasalam@pc.ola.org',
    ridingName: 'Scarborough—Rouge Park',
  },
  {
    firstName: 'Lisa',
    lastName: 'Thompson',
    email: 'lisa.thompson@pc.ola.org',
    ridingName: 'Huron—Bruce',
  },
  {
    firstName: 'Michael A.',
    lastName: 'Tibollo',
    email: 'michael.tibolloCO@pc.ola.org',
    ridingName: 'Vaughan—Woodbridge',
  },
  {
    firstName: 'Effie J.',
    lastName: 'Triantafilopoulos',
    email: 'effie.triantafilopoulos@pc.ola.org',
    ridingName: 'Oakville North—Burlington',
  },
  {
    firstName: 'John',
    lastName: 'Vanthof',
    email: 'jvanthof-qp@ndp.on.ca',
    ridingName: 'Timiskaming—Cochrane',
  },
  {
    firstName: 'Daisy',
    lastName: 'Wai',
    email: 'daisy.wai@pc.ola.org',
    ridingName: 'Richmond Hill',
  },
  {
    firstName: 'Bill',
    lastName: 'Walker',
    email: 'bill.walker@pc.ola.org',
    ridingName: 'Bruce—Grey—Owen Sound',
  },
  {
    firstName: 'Jamie',
    lastName: 'West',
    email: 'JWest-QP@ndp.on.ca',
    ridingName: 'Sudbury',
  },
  {
    firstName: 'Jim',
    lastName: 'Wilson',
    email: 'jwilson@ola.org',
    ridingName: 'Simcoe—Grey',
  },
  {
    firstName: 'Kathleen O.',
    lastName: 'Wynne',
    email: 'kwynne.mpp.co@liberal.ola.org',
    ridingName: 'Don Valley West',
  },
  {
    firstName: 'John',
    lastName: 'Yakabuski',
    email: 'john.yakabuski@pc.ola.org',
    ridingName: 'Renfrew—Nipissing—Pembroke',
  },
  {
    firstName: 'Kevin',
    lastName: 'Yarde',
    email: 'KYarde-QP@ndp.on.ca',
    ridingName: 'Brampton North',
  },
  {
    firstName: 'Jeff',
    lastName: 'Yurek',
    email: 'jeff.yurek@pc.ola.org',
    ridingName: 'Elgin—Middlesex—London',
  },
]
