export const MPS = [
  {
    firstName: 'Deepak',
    lastName: 'Anand',
    email: 'deepak.anand@pc.ola.org',
    ridingName: 'Mississauga—Malton',
  },
  {
    firstName: 'Jill',
    lastName: 'Andrew',
    email: 'JAndrew-QP@ndp.on.ca',
    ridingName: "Toronto—St. Paul's",
  },
  {
    firstName: 'Teresa',
    lastName: 'Armstrong',
    email: 'tarmstrong-qp@ndp.on.ca',
    ridingName: 'London—Fanshawe',
  },
  {
    firstName: 'Ted',
    lastName: 'Arnott',
    email: 'ted.arnott@pc.ola.org',
    ridingName: 'Wellington—Halton Hills',
  },
  {
    firstName: 'Ian',
    lastName: 'Arthur',
    email: 'IArthur-QP@ndp.on.ca',
    ridingName: 'Kingston and the Islands',
  },
  {
    firstName: 'Roman',
    lastName: 'Baber',
    email: 'rbaber@ola.org',
    ridingName: 'York Centre',
  },
  {
    firstName: 'Aris',
    lastName: 'Babikian',
    email: 'aris.babikian@pc.ola.org',
    ridingName: 'Scarborough—Agincourt',
  },
  {
    firstName: 'Doly',
    lastName: 'Begum',
    email: 'DBegum-QP@ndp.on.ca',
    ridingName: 'Scarborough Southwest',
  },
  {
    firstName: 'Jessica',
    lastName: 'Bell',
    email: 'JBell-QP@ndp.on.ca',
    ridingName: 'University—Rosedale',
  },
  {
    firstName: 'Rima',
    lastName: 'Berns-McGown',
    email: 'RBerns-McGown-QP@ndp.on.ca',
    ridingName: 'Beaches—East York',
  },
  {
    firstName: 'Gilles',
    lastName: 'Bisson',
    email: 'gbisson@ndp.on.ca',
    ridingName: 'Timmins',
  },
  {
    firstName: 'Stephen',
    lastName: 'Blais',
    email: 'sblais.mpp.co@liberal.ola.org',
    ridingName: 'Orléans',
  },
  {
    firstName: 'Guy',
    lastName: 'Bourgouin',
    email: 'GBourgouin-QP@ndp.on.ca',
    ridingName: 'Mushkegowuk—James Bay',
  },
  {
    firstName: 'Jeff',
    lastName: 'Burch',
    email: 'JBurch-QP@ndp.on.ca',
    ridingName: 'Niagara Centre',
  },
  {
    firstName: 'Paul',
    lastName: 'Calandra',
    email: 'paul.calandra@pc.ola.org',
    ridingName: 'Markham—Stouffville',
  },
  {
    firstName: 'Lorne',
    lastName: 'Coe',
    email: 'lorne.coe@pc.ola.org',
    ridingName: 'Whitby',
  },
  {
    firstName: 'Lucille',
    lastName: 'Collard',
    email: 'LCollard.mpp.co@liberal.ola.org',
    ridingName: 'Ottawa—Vanier',
  },
  {
    firstName: 'Michael',
    lastName: 'Coteau',
    email: 'mcoteau.mpp.co@liberal.ola.org',
    ridingName: 'Don Valley East',
  },
  {
    firstName: 'Amy',
    lastName: 'Fee',
    email: 'amy.fee@pc.ola.org',
    ridingName: 'Kitchener South—Hespeler',
  },
  {
    firstName: 'Catherine',
    lastName: 'Fife',
    email: 'cfife-qp@ndp.on.ca',
    ridingName: 'Waterloo',
  },
  {
    firstName: 'Doug',
    lastName: 'Ford',
    email: 'doug.fordco@pc.ola.org',
    ridingName: 'Etobicoke North',
  },
  {
    firstName: 'John',
    lastName: 'Fraser',
    email: 'Jfraser.mpp.co@liberal.ola.org',
    ridingName: 'Ottawa South',
  },
  {
    firstName: 'Jennifer',
    lastName: 'French',
    email: 'JFrench-QP@ndp.on.ca',
    ridingName: 'Oshawa',
  },
  {
    firstName: 'Wayne',
    lastName: 'Gates',
    email: 'wgates-qp@ndp.on.ca',
    ridingName: 'Niagara Falls',
  },
  {
    firstName: 'Goldie',
    lastName: 'Ghamari',
    email: 'goldie.ghamari@pc.ola.org',
    ridingName: 'Carleton',
  },
  {
    firstName: 'Chris',
    lastName: 'Glover',
    email: 'CGlover-CO@ndp.on.ca',
    ridingName: 'Spadina—Fort York',
  },
  {
    firstName: 'Michael',
    lastName: 'Gravelle',
    email: 'mgravelle.mpp.co@liberal.ola.org',
    ridingName: 'Thunder Bay—Superior North',
  },
  {
    firstName: 'Lisa',
    lastName: 'Gretzky',
    email: 'LGretzky-QP@ndp.on.ca',
    ridingName: 'Windsor West',
  },
  {
    firstName: 'France',
    lastName: 'Gélinas',
    email: 'fgelinas-qp@ndp.on.ca',
    ridingName: 'Nickel Belt',
  },
  {
    firstName: 'Joel',
    lastName: 'Harden',
    email: 'JHarden-QP@ndp.on.ca',
    ridingName: 'Ottawa Centre',
  },
  {
    firstName: 'Faisal',
    lastName: 'Hassan',
    email: 'FHassan-QP@ndp.on.ca',
    ridingName: 'York South—Weston',
  },
  {
    firstName: 'Percy',
    lastName: 'Hatfield',
    email: 'PHatfield-QP@ndp.on.ca',
    ridingName: 'Windsor—Tecumseh',
  },
  {
    firstName: 'Randy',
    lastName: 'Hillier',
    email: 'RHillier-CO@ola.org',
    ridingName: 'Lanark—Frontenac—Kingston',
  },
  {
    firstName: 'Andrea',
    lastName: 'Horwath',
    email: 'horwatha-qp@ndp.on.ca',
    ridingName: 'Hamilton Centre',
  },
  {
    firstName: 'Mitzie',
    lastName: 'Hunter',
    email: 'mhunter.mpp.co@liberal.ola.org',
    ridingName: 'Scarborough—Guildwood',
  },
  {
    firstName: 'Logan',
    lastName: 'Kanapathi',
    email: 'logan.kanapathi@pc.ola.org',
    ridingName: 'Markham—Thornhill',
  },
  {
    firstName: 'Belinda',
    lastName: 'Karahalios',
    email: 'bkarahalios@ola.org',
    ridingName: 'Cambridge',
  },
  {
    firstName: 'Bhutila',
    lastName: 'Karpoche',
    email: 'BKarpoche-QP@ndp.on.ca',
    ridingName: 'Parkdale—High Park',
  },
  {
    firstName: 'Terence',
    lastName: 'Kernaghan',
    email: 'TKernaghan-QP@ndp.on.ca',
    ridingName: 'London North Centre',
  },
  {
    firstName: 'Daryl',
    lastName: 'Kramp',
    email: 'daryl.kramp@pc.ola.org',
    ridingName: 'Hastings—Lennox and Addington',
  },
  {
    firstName: 'Laura Mae',
    lastName: 'Lindo',
    email: 'LLindo-QP@ndp.on.ca',
    ridingName: 'Kitchener Centre',
  },
  {
    firstName: 'Sol',
    lastName: 'Mamakwa',
    email: 'SMamakwa-QP@ndp.on.ca',
    ridingName: 'Kiiwetinoong',
  },
  {
    firstName: 'Michael',
    lastName: 'Mantha',
    email: 'mmantha-qp@ndp.on.ca',
    ridingName: 'Algoma—Manitoulin',
  },
  {
    firstName: 'Gila',
    lastName: 'Martow',
    email: 'gila.martow@pc.ola.org',
    ridingName: 'Thornhill',
  },
  {
    firstName: 'Paul',
    lastName: 'Miller',
    email: 'pmiller-qp@ndp.on.ca',
    ridingName: 'Hamilton East—Stoney Creek',
  },
  {
    firstName: 'Christina',
    lastName: 'Mitas',
    email: 'christina.mitas@pc.ola.org',
    ridingName: 'Scarborough Centre',
  },
  {
    firstName: 'Judith',
    lastName: 'Monteith-Farrell',
    email: 'JMonteith-Farrell-QP@ndp.on.ca',
    ridingName: 'Thunder Bay—Atikokan',
  },
  {
    firstName: 'Suze',
    lastName: 'Morrison',
    email: 'SMorrison-QP@ndp.on.ca',
    ridingName: 'Toronto Centre',
  },
  {
    firstName: 'Taras',
    lastName: 'Natyshak',
    email: 'tnatyshak-qp@ndp.on.ca',
    ridingName: 'Essex',
  },
  {
    firstName: 'Rick',
    lastName: 'Nicholls',
    email: 'rick.nicholls@pc.ola.org',
    ridingName: 'Chatham-Kent—Leamington',
  },
  {
    firstName: 'Rod',
    lastName: 'Phillips',
    email: 'rod.phillips@pc.ola.org',
    ridingName: 'Ajax',
  },
  {
    firstName: 'Tom',
    lastName: 'Rakocevic',
    email: 'TRakocevic-QP@ndp.on.ca',
    ridingName: 'Humber River—Black Creek',
  },
  {
    firstName: 'Kaleed',
    lastName: 'Rasheed',
    email: 'kaleed.rasheed@pc.ola.org',
    ridingName: 'Mississauga East—Cooksville',
  },
  {
    firstName: 'Amarjot',
    lastName: 'Sandhu',
    email: 'amarjot.sandhu@pc.ola.org',

    ridingName: 'Brampton West',
  },
  {
    firstName: 'Peggy',
    lastName: 'Sattler',
    email: 'Psattler-qp@ndp.on.ca',
    ridingName: 'London West',
  },
  {
    firstName: 'Mike',
    lastName: 'Schreiner',

    email: 'Mschreiner@ola.org',

    ridingName: 'Guelph',
  },
  {
    firstName: 'Sandy',
    lastName: 'Shaw',

    email: 'SShaw-CO@ndp.on.ca',

    ridingName: 'Hamilton West—Ancaster—Dundas',
  },
  {
    firstName: 'Amanda',
    lastName: 'Simard',

    email: 'asimard.mpp@liberal.ola.org',

    ridingName: 'Glengarry—Prescott—Russell',
  },
  {
    firstName: 'Gurratan',
    lastName: 'Singh',
    email: 'GSingh-QP@ndp.on.ca',
    ridingName: 'Brampton East',
  },
  {
    firstName: 'Sara',
    lastName: 'Singh',
    email: 'SSingh-QP@ndp.on.ca',
    ridingName: 'Brampton Centre',
  },
  {
    firstName: 'Jennifer (Jennie)',
    lastName: 'Stevens',
    email: 'JStevens-QP@ndp.on.ca',
    ridingName: 'St. Catharines',
  },
  {
    firstName: 'Marit',
    lastName: 'Stiles',
    email: 'MStiles-QP@ndp.on.ca',
    ridingName: 'Davenport',
  },
  {
    firstName: 'Peter',
    lastName: 'Tabuns',
    email: 'tabunsp-qp@ndp.on.ca',
    ridingName: 'Toronto—Danforth',
  },
  {
    firstName: 'Monique',
    lastName: 'Taylor',
    email: 'mtaylor-qp@ndp.on.ca',
    ridingName: 'Hamilton Mountain',
  },
  {
    firstName: 'John',
    lastName: 'Vanthof',
    email: 'jvanthof-qp@ndp.on.ca',
    ridingName: 'Timiskaming—Cochrane',
  },
  {
    firstName: 'Jamie',
    lastName: 'West',
    email: 'JWest-QP@ndp.on.ca',
    ridingName: 'Sudbury',
  },
  {
    firstName: 'Jim',
    lastName: 'Wilson',
    email: 'jwilson@ola.org',
    ridingName: 'Simcoe—Grey',
  },
  {
    firstName: 'Kathleen O.',
    lastName: 'Wynne',
    email: 'kwynne.mpp.co@liberal.ola.org',
    ridingName: 'Don Valley West',
  },
  {
    firstName: 'Kevin',
    lastName: 'Yarde',
    email: 'KYarde-QP@ndp.on.ca',
    ridingName: 'Brampton North',
  },
]
